# baseURL = "https://example.org/"
languageCode = "en-us"
title = "NEU Pi Delta Psi"
# theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    languageCode = "en-us"
    logo = "images/logo.png"
    author = "NEU PDP"
    description = "Official site for the Alpha Alpha Chapter of Pi Delta Psi"
    dateFormat = "January 2, 2006"

    weight = 2
    # home = "HOME"
    # about = "ABOUT"
    # other = "SERVICE"
    # other = "ACTIVE HOUSE"
    # other = "BLOG"
    # other = "CONTACT"

    #FOOTER
    footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "Excellence Through Brotherhood"
        description = "Northeastern Pi Delta Psi prides itself on empowering a new generation of Brothers academically, culturally, and righteously."
        button  = false
        btnText = "Know More" # TODO: Change
        btnURL  = "https://pideltapsi.com/" # TODO: Change
        videoThumb = "images/slider/video-player-thumb.jpg" # TODO: Change
        videoURL   = "https://www.youtube.com/embed/-lWqB_cl6Sk"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "We have explored the digital landscape with passion for a long time"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
