languageCode = "en-us"
title = "NEU Pi Delta Psi"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    languageCode = "en-us"
    logo = "images/logo.png"
    author = "NEU PDP"
    description = "Official site for the Alpha Alpha Chapter of Pi Delta Psi"
    dateFormat = "January 2, 2006"

    weight = 2

    #FOOTER
    footerDescription = "This site belongs to the Alpha Alpha Chapter of Pi Delta Psi Fraternity Inc. Northeastern University"
    # footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "Excellence Through Brotherhood"
        description = "Northeastern Pi Delta Psi prides itself on empowering a new generation of Brothers academically, culturally, and righteously."
        button  = false
        btnText = "Know More" # TODO: Change
        btnURL  = "https://pideltapsi.com/" # TODO: Change
        videoThumb = "images/slider/video-player-thumb.jpg" # TODO: Change
        videoURL   = "https://www.youtube.com/embed/-lWqB_cl6Sk"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "We are the fastest growing Asian-American fraternity in the United States"
        description = "Pi Delta Psi is an Asian American Cultural Fraternity founded on February 20, 1994 at Binghamton University in Binghamton, New York. Since our founding, the primary mission of Pi Delta Psi has been to spread Asian American Cultural awareness in an effort to empower the entire Asian American community. We are guided by four pillars; Academic Achievement, Cultural Awareness, Righteousness, and Friendship/Loyalty. The Northeastern University Chapter was established in 2005, and since then we have grown to be 143 brothers strong."
    
    # Blog Section On Homepage
    [params.blog] # TODO: Disabled blog for now
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "LET'S TALK"
        title   = "Contact Us."
        subtitle= "We'd love to get in contact if you have any questions or concerns."
        address = "360 Huntington Ave, Boston, MA 02115, U.S.A"
        email   = "President.AlphaAlpha@pideltapsi.com"
        # fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/northeastern.pideltapsi/"
        # twitter = "https://twitter.com/"
        # linkedin= "https://www.linkedin.com/"
        # dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/neupdpsi"
        mapLatitude = "42.3402"
        mapLongitude= "71.0893"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's get in Contact!"
        subtitle= "We value any questions you may have, whether you are a curious student, Brother from another chapter, or School official, please don't hesitate to reach out! "
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    # [[menu.nav]]
    #     name    = "service"
    #     url     = "service"
    #     weight  = 3
    # [[menu.nav]]
    #     name    = "portfolio"
    #     url     = "portfolio"
    #     weight  = 4
    # [[menu.nav]]
    #     name    = "blog"
    #     url     = "blog"
    #     weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 3

    # Footer Service Menu
    # [[menu.service]]
    #     name    = "graphicdesign"
    #     url     = "service"
    #     weight  = 1
    # [[menu.service]]
    #     name    = "webdesign"
    #     url     = "service"
    #     weight  = 2
    # [[menu.service]]
    #     name    = "webdevelopment"
    #     url     = "service"
    #     weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "contact"
        url     = "contact"
        weight  = 2
    # [[menu.quicklink]]
    #     name    = "faqs"
    #     url     = "about"
    #     weight  = 3
    # [[menu.quicklink]]
    #     name    = "badges"
    #     url     = "about"
    #     weight  = 4
